package finam.client.enums;

import lombok.Getter;

@Getter
public enum OrderStatusEnum {
    ORDER_STATUS_UNSPECIFIED(0),
    ORDER_STATUS_NEW(1),
    ORDER_STATUS_PARTIALLY_FILLED(2),
    ORDER_STATUS_FILLED(3),
    ORDER_STATUS_DONE_FOR_DAY(4),
    ORDER_STATUS_CANCELED(5),
    ORDER_STATUS_REPLACED(6),
    ORDER_STATUS_PENDING_CANCEL(7),
    ORDER_STATUS_REJECTED(9),
    ORDER_STATUS_SUSPENDED(10),
    ORDER_STATUS_PENDING_NEW(11),
    ORDER_STATUS_EXPIRED(13),
    ORDER_STATUS_FAILED(16),
    ORDER_STATUS_FORWARDING(17),
    ORDER_STATUS_WAIT(18),
    ORDER_STATUS_DENIED_BY_BROKER(19),
    ORDER_STATUS_REJECTED_BY_EXCHANGE(20),
    ORDER_STATUS_WATCHING(21),
    ORDER_STATUS_EXECUTED(22),
    ORDER_STATUS_DISABLED(23),
    ORDER_STATUS_LINK_WAIT(24),
    ORDER_STATUS_SL_GUARD_TIME(27),
    ORDER_STATUS_SL_EXECUTED(28),
    ORDER_STATUS_SL_FORWARDING(29),
    ORDER_STATUS_TP_GUARD_TIME(30),
    ORDER_STATUS_TP_EXECUTED(31),
    ORDER_STATUS_TP_CORRECTION(32),
    ORDER_STATUS_TP_FORWARDING(33),
    ORDER_STATUS_TP_CORR_GUARD_TIME(34);

    private final int number;

    OrderStatusEnum(int number) {
        this.number = number;
    }
}