package finam.client.enums;

public enum QuoteLevelEnum {
    QUOTE_LEVEL_UNSPECIFIED,
    QUOTE_LEVEL_LAST_PRICE,
    QUOTE_LEVEL_BEST_BID_OFFER,
    QUOTE_LEVEL_DEPTH_OF_MARKET,
    QUOTE_LEVEL_DEPTH_OF_BOOK,
    QUOTE_LEVEL_ACCESS_FORBIDDEN
}
