spring.application.name=ClientFinamApplication

server.port=${SERVER_PORT}
webclient.base-url=https://api.finam.ru
excluded.paths=/swagger-ui/*, /v3/api-docs/**
refresh.token.interval.ms=600000
secret.finam.key=${SECRET_KEY}
hash.api.key=${API_KEY}

info.app.name=Java Client for Finam REST API
info.app.version=1.1.1
info.app.description=Client library for interacting with Finam services via REST API.\nDocumentation is available at: https://tradeapi.finam.ru/docs/guides/rest\nCurrent Finam version: 2.10.0 (December 11, 2025)

